name: Build sqlite3_rsync

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        arch: [x64]
        include:
          - os: ubuntu-latest
            arch: arm
            build-platform: linux-arm
          - os: ubuntu-latest
            arch: arm64
            build-platform: linux-arm64
          - os: macos-latest
            arch: arm64
            build-platform: macos-arm64
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Cache SQLite repository
      uses: actions/cache@v4
      with:
        path: ./sqlite
        key: sqlite-repo-${{ runner.os }}-${{ matrix.arch }}-${{ hashFiles('**/sqlite/.git/HEAD') }}
        restore-keys: |
          sqlite-repo-${{ runner.os }}-${{ matrix.arch }}-

    - name: Set up environment (Windows)
      if: matrix.os == 'windows-latest'
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: mingw-w64-x86_64-gcc mingw-w64-x86_64-make mingw-w64-x86_64-autoconf mingw-w64-x86_64-automake git zip

    - name: Set up environment (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc g++ make autoconf automake git zip
        if [ "${{ matrix.arch }}" = "arm" ] || [ "${{ matrix.arch }}" = "arm64" ]; then
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
        fi

    - name: Set up environment (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install git zip autoconf automake
        xcode-select --install || true

    - name: Clone or update SQLite repository
      shell: bash
      run: |
        if [ -d "sqlite" ]; then
          cd sqlite
          git fetch origin
          git checkout sqlite3-rsync
        else
          git clone https://github.com/sqlite/sqlite.git
          cd sqlite
          git checkout sqlite3-rsync
        fi

    - name: Generate configure script
      working-directory: ./sqlite
      shell: msys2 {0}
      if: matrix.os == 'windows-latest'
      run: |
        autoconf
        ls -l configure

    - name: Generate configure script (Linux and macOS)
      if: matrix.os != 'windows-latest'
      working-directory: ./sqlite
      run: |
        autoconf
        ls -l configure

    - name: Generate sqlite3.c
      working-directory: ./sqlite
      shell: msys2 {0}
      if: matrix.os == 'windows-latest'
      run: |
        ./configure
        mingw32-make sqlite3.c
        ls -l sqlite3.c

    - name: Generate sqlite3.c (Linux and macOS)
      if: matrix.os != 'windows-latest'
      working-directory: ./sqlite
      run: |
        ./configure
        make sqlite3.c
        ls -l sqlite3.c

    - name: Compile sqlite3-rsync (Windows x64)
      if: matrix.os == 'windows-latest' && matrix.arch == 'x64'
      working-directory: ./sqlite/tool
      shell: msys2 {0}
      run: |
        gcc -o sqlite3-rsync.exe sqlite3-rsync.c ../sqlite3.c -DSQLITE_ENABLE_DBPAGE_VTAB
        ./sqlite3-rsync.exe --help

    - name: Compile sqlite3-rsync (Linux x64)
      if: matrix.os == 'ubuntu-latest' && matrix.arch == 'x64'
      working-directory: ./sqlite/tool
      run: |
        gcc -o sqlite3-rsync sqlite3-rsync.c ../sqlite3.c -DSQLITE_ENABLE_DBPAGE_VTAB
        ./sqlite3-rsync --help

    - name: Compile sqlite3-rsync (Linux ARM)
      if: matrix.os == 'ubuntu-latest' && matrix.arch == 'arm'
      working-directory: ./sqlite/tool
      run: |
        aarch64-linux-gnu-gcc -o sqlite3-rsync sqlite3-rsync.c ../sqlite3.c -DSQLITE_ENABLE_DBPAGE_VTAB
        file sqlite3-rsync

    - name: Compile sqlite3-rsync (Linux ARM64)
      if: matrix.os == 'ubuntu-latest' && matrix.arch == 'arm64'
      working-directory: ./sqlite/tool
      run: |
        aarch64-linux-gnu-gcc -o sqlite3-rsync sqlite3-rsync.c ../sqlite3.c -DSQLITE_ENABLE_DBPAGE_VTAB
        file sqlite3-rsync

    - name: Compile sqlite3-rsync (macOS x64)
      if: matrix.os == 'macos-latest' && matrix.arch == 'x64'
      working-directory: ./sqlite/tool
      run: |
        arch -x86_64 gcc -o sqlite3-rsync sqlite3-rsync.c ../sqlite3.c -DSQLITE_ENABLE_DBPAGE_VTAB
        ./sqlite3-rsync --help

    - name: Compile sqlite3-rsync (macOS ARM64)
      if: matrix.os == 'macos-latest' && matrix.arch == 'arm64'
      working-directory: ./sqlite/tool
      run: |
        arch -arm64 gcc -o sqlite3-rsync sqlite3-rsync.c ../sqlite3.c -DSQLITE_ENABLE_DBPAGE_VTAB
        ./sqlite3-rsync --help

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: sqlite3-rsync-${{ matrix.os }}-${{ matrix.arch }}
        path: ./sqlite/tool/sqlite3-rsync*

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Create archive
      run: |
        mkdir -p release
        find artifacts -type f -name 'sqlite3-rsync*' -exec cp {} release/ \;
        cd release
        zip -r ../sqlite3-rsync-binaries-${{ github.ref_name }}.zip .
      shell: bash

    - name: Upload to release
      uses: softprops/action-gh-release@v2
      with:
        files: sqlite3-rsync-binaries-${{ github.ref_name }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}